---
kind: pipeline
type: ssh
name: promotion-testing

clone:
  disable: true

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: build-gencache
    commands:
      - git clone https://github.com/EasyRPG/Tools.git
      - cd ./Tools/gencache
      - ./bootstrap # only needed if using a git checkout
      - ./configure
      - make
trigger:
  event:
    - promote
  target:
    - testing
---
kind: signature
hmac: d79f450e58a15d89c6976b00eed859fe033da4e1297cf980466462ac6175029f

...
