---
kind: pipeline
type: ssh
name: ssh-deploy-prod

clone:
  disable: true

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: build-gencache
    commands:
      - git clone https://github.com/EasyRPG/Tools.git
      - cd ./Tools/gencache
      - ./bootstrap # only needed if using a git checkout
      - ./configure
      - make
trigger:
  branch:
    - main
  event:
    - push

---
kind: signature
hmac: b90013711027567da409595948f7df2402ae172a8c87a94394b24b2ddf8ec165

...
