---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/EasyRPG/Tools.git
  - name: build-gencache
    image: ubuntu:20.04
    commands:
      - cd ./Tools/gencache
      - ./bootstrap # only needed if using a git checkout
      - ./configure
      - make
---
kind: signature
hmac: f877a36063d96b4656b010807e89547a329250c4a25aa1775b12cef5b0b20a01

...
